# Generated by Django 3.2.13 on 2023-01-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='TITLE')),
                ('pos', models.CharField(choices=[('T01', 'T01'), ('T02', 'T02')], default='None', max_length=50, verbose_name='POSITION')),
                ('video', models.FileField(upload_to='upload/video/%y')),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=20, verbose_name='STATUS')),
                ('result', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], max_length=30, null=True, verbose_name='RESULT')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='UPLOAD DATE')),
            ],
            options={
                'ordering': ('upload_dt',),
            },
        ),
    ]
